In [1]:
from sklearn.linear_model import LogisticRegression

In [2]:
import pandas as pd

In [3]:
matrix = pd.read_csv('minute-matrix.csv')

In [4]:
matrix.head()

,season,round,tie,made_minute,away,t1goal,t2goal,t1awaygoal,t2awaygoal,t1goals,t2goals,t1goal_diff,t1awaygoals,t2awaygoals,t1awaygoal_diff,t1,t2,winner,t1win
0,2008,first,arsenal-milan,1.0,NaN,False,False,False,False,0,0,0,0,0,0,arsenal,milan,arsenal,1
1,2008,first,arsenal-milan,2.0,NaN,False,False,False,False,0,0,0,0,0,0,arsenal,milan,arsenal,1
2,2008,first,arsenal-milan,3.0,NaN,False,False,False,False,0,0,0,0,0,0,arsenal,milan,arsenal,1
3,2008,first,arsenal-milan,4.0,NaN,False,False,False,False,0,0,0,0,0,0,arsenal,milan,arsenal,1
4,2008,first,arsenal-milan,5.0,NaN,False,False,False,False,0,0,0,0,0,0,arsenal,milan,arsenal,1

In [42]:
matrix.tail()

,season,round,tie,made_minute,away,t1goal,t2goal,t1awaygoal,t2awaygoal,t1goals,t2goals,t1goal_diff,t1awaygoals,t2awaygoals,t1awaygoal_diff,t1,t2,winner,t1win
30236,2019,first,united-psg,180.0,NaN,False,False,False,False,2,3,-1,2,2,0,united,psg,united,1
30237,2019,first,united-psg,181.0,NaN,False,False,False,False,2,3,-1,2,2,0,united,psg,united,1
30238,2019,first,united-psg,182.0,NaN,False,False,False,False,2,3,-1,2,2,0,united,psg,united,1
30239,2019,first,united-psg,183.0,NaN,False,False,False,False,2,3,-1,2,2,0,united,psg,united,1
30240,2019,first,united-psg,184.0,a,True,False,True,False,3,3,0,3,2,1,united,psg,united,1

In [35]:
X = matrix[[
    'made_minute',
#     't1goals','t2goals',
    't1goal_diff',
#     't1awaygoals','t2awaygoals',
    't1awaygoal_diff',
#     't1win'
]].values

In [36]:
y = matrix['t1win'].values

In [37]:
lrmodel = LogisticRegression(random_state=41, solver='liblinear')

In [38]:
from sklearn import model_selection

In [39]:
scores = model_selection.cross_val_score(lrmodel, X, y, cv=10)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.76 (+/- 0.09)

In [40]:
model.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=41, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [46]:
matrix['probt1win'] = [l[1] for l in model.predict_proba(X)]

In [48]:
matrix.to_csv('sklearn-pred-prob.csv', index=False)